/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCard: typeof import('@gouvminint/vue-dsfr')['DsfrCard']
    DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
    DsfrConsent: typeof import('@gouvminint/vue-dsfr')['DsfrConsent']
    DsfrFieldset: typeof import('@gouvminint/vue-dsfr')['DsfrFieldset']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrHighlight: typeof import('@gouvminint/vue-dsfr')['DsfrHighlight']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrLegend: typeof import('@gouvminint/vue-dsfr')['DsfrLegend']
    DsfrNewsLetter: typeof import('@gouvminint/vue-dsfr')['DsfrNewsLetter']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrPicture: typeof import('@gouvminint/vue-dsfr')['DsfrPicture']
    DsfrQuote: typeof import('@gouvminint/vue-dsfr')['DsfrQuote']
    DsfrSearch: typeof import('@gouvminint/vue-dsfr')['DsfrSearch']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrSerlect: typeof import('@gouvminint/vue-dsfr')['DsfrSerlect']
    DsfrTags: typeof import('@gouvminint/vue-dsfr')['DsfrTags']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    DsfrTiles: typeof import('@gouvminint/vue-dsfr')['DsfrTiles']
    DsfrTooltip: typeof import('@gouvminint/vue-dsfr')['DsfrTooltip']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
