/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationList: typeof import('./components/ApplicationList.vue')['default']
    ApplicationOverview: typeof import('./components/ApplicationOverview.vue')['default']
    ApplicationsTiles: typeof import('./components/ApplicationsTiles.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    Description: typeof import('./components/Description.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBreadcrumb: typeof import('@gouvminint/vue-dsfr')['DsfrBreadcrumb']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCard: typeof import('@gouvminint/vue-dsfr')['DsfrCard']
    DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
    DsfrConsent: typeof import('@gouvminint/vue-dsfr')['DsfrConsent']
    DsfrFieldset: typeof import('@gouvminint/vue-dsfr')['DsfrFieldset']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrHighlight: typeof import('@gouvminint/vue-dsfr')['DsfrHighlight']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrLegend: typeof import('@gouvminint/vue-dsfr')['DsfrLegend']
    DsfrNewsLetter: typeof import('@gouvminint/vue-dsfr')['DsfrNewsLetter']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrPicture: typeof import('@gouvminint/vue-dsfr')['DsfrPicture']
    DsfrQuote: typeof import('@gouvminint/vue-dsfr')['DsfrQuote']
    DsfrSearch: typeof import('@gouvminint/vue-dsfr')['DsfrSearch']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrSerlect: typeof import('@gouvminint/vue-dsfr')['DsfrSerlect']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabItem: typeof import('@gouvminint/vue-dsfr')['DsfrTabItem']
    DsfrTable: typeof import('@gouvminint/vue-dsfr')['DsfrTable']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTags: typeof import('@gouvminint/vue-dsfr')['DsfrTags']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    DsfrTiles: typeof import('@gouvminint/vue-dsfr')['DsfrTiles']
    DsfrTooltip: typeof import('@gouvminint/vue-dsfr')['DsfrTooltip']
    ExportApplication: typeof import('./components/ExportApplication.vue')['default']
    ExportApplications: typeof import('./components/ExportApplications.vue')['default']
    ExportButton: typeof import('./components/ExportButton.vue')['default']
    'InformationsGénéral': typeof import('./components/InformationsGénérales.vue')['default']
    InformationsGenerales: typeof import('./components/InformationsGenerales.vue')['default']
    LastModifiedApplications: typeof import('./components/LastModifiedApplications.vue')['default']
    Objectifs: typeof import('./components/Objectifs.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchApplications: typeof import('./components/SearchApplications.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
