/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBreadcrumb: typeof import('@gouvminint/vue-dsfr')['DsfrBreadcrumb']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabItem: typeof import('@gouvminint/vue-dsfr')['DsfrTabItem']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTag: typeof import('@gouvminint/vue-dsfr')['DsfrTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
