include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  REGISTRY_URL: ${REGISTRY_HOST}/${PROJECT_PATH}

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

build-backend:
  variables:
    WORKING_DIR: ./backend
    DOCKERFILE: ./backend/Dockerfile
    IMAGE_NAMES: ref-app-back:${CI_COMMIT_SHORT_SHA} ref-app-back:${CI_COMMIT_REF_NAME}
  stage: docker-build
  extends:
    - .kaniko:build-push
  # Triggers job only if a file in the server directory changed in current commit
  # rules:
  #   - changes:
  #     - server/**/*

build-frontend:
  variables:
    WORKING_DIR: ./frontend
    DOCKERFILE: ./frontend/Dockerfile
    IMAGE_NAMES: ref-app-front:${CI_COMMIT_SHORT_SHA} ref-app-front:${CI_COMMIT_REF_NAME}
  stage: docker-build
  extends:
    - .kaniko:build-push
  # Triggers job only if a file in the client directory changed in current commit
  # rules:
  #   - changes:
  #     - client/**/*
