include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  REGISTRY_URL: ${REGISTRY_HOST}/${PROJECT_PATH}

stages:
  - read-secret
  - docker-buildapp

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-buildapp:
  variables:
    WORKING_DIR: ./
    DOCKERFILE: ./Dockerfile.app
    IMAGE_NAMES: ref-app-back:${CI_COMMIT_SHORT_SHA} ref-app-back:${CI_COMMIT_REF_NAME}
  stage: docker-buildapp
  extends:
    - .kaniko:build-push
