version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: canelbdd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - my-network

  backend:
    image: bitnami/node:22
    container_name: backend
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/canelbdd
    depends_on:
      - postgres
    ports:
      - "3500:3500"
    volumes:
      - ./server:/app
    working_dir: /app
    entrypoint: sh -c "sleep 10 && npm install -g pnpm && pnpm install && pnpm run start:dev"
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: myuser
      DB_PASSWORD: mypassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm.json
      # Fixer la clé secrète
      KEYCLOAK_CLIENT_SECRET: xrSK3UlEQcHhqmUXyhlKMKg0fEQPfQBI
    ports:
      - "8082:8080"
    volumes:
      - ./temp/realm.json:/realm.json
      - keycloak_data:/opt/keycloak/data
    entrypoint: ["/opt/keycloak/bin/kc.sh"]
    command: ["start-dev"]
    depends_on:
      - postgres
    networks:
      - my-network

  client:
    image: node:22
    container_name: vue_client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    environment:
      VITE_KEYCLOAK_AUTH_SERVER_URL: http://localhost:8082
      VITE_KEYCLOAK_REALM: referentiel-applications
      VITE_KEYCLOAK_CLIENT_ID: referentiel-applications
      VITE_KEYCLOAK_CLIENT_SECRET: xrSK3UlEQcHhqmUXyhlKMKg0fEQPfQBI
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  postgres_data:
  keycloak_data:

networks:
  my-network:
    driver: bridge
