version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: canelbdd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - my-network

  backend:
    image: node:latest
    container_name: backend
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/canelbdd
    depends_on:
      - postgres
    ports:
      - "3500:3500"
    volumes:
<<<<<<< HEAD
      - ./:/app
=======
      - .:/app
>>>>>>> deaacbb (add prisma seed.ts)
    working_dir: /app
    entrypoint: sh -c "sleep 10 && npm install && npm run start:dev"
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8082
      KEYCLOAK_REALM: referentiel-applications
      KEYCLOAK_CLIENT_ID: referentiel-applications-api
      KEYCLOAK_CLIENT_SECRET: HbOh6jTkUiOLMB8H8KUZs048KMRQ7y9g
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm.json
    ports:
      - "8082:8080"
    volumes:
      - ./temp/realm.json:/realm.json
    entrypoint: ["/opt/keycloak/bin/kc.sh"]
    command: ["start-dev"]
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
