name: dispatch to infra

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:

jobs:
  dispatch:
    runs-on: canel

    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3

      - name: Dispatch Event
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PRESONAL_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dnum-mi/referentiel-applications-infra/dispatches \
            -d '{
              "event_type": "run-infra",
              "client_payload": {
                "build_sha": "${{ github.event.pull_request.head.sha }}"
              }
            }'
