name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/dnum-mi/referentiel-applications/backend
      context: ./server

  build-frontend:
    name: Build Frontend
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/dnum-mi/referentiel-applications/frontend
      context: ./client

  test-format:
    name: Test Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Prettier check
        run: |
          npm ci
          npm run format-check
